# Site settings
title: Code Culture
email: contact@codeculture.guru
description: > # Writer Theme is a responsive template
 A blog about code of conduct for coding.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://simplyamuthan.github.io" # the base hostname & protocol for your site
enable_retina: true
permalink: :title
nav_list:
  Home : ['Home', '/', 'fa-home']
 # Home_Alt : ['Home Alt', '/home-alt', 'fa-home']
 # Home_Alt_2 : ['Home Alt 2', '/home-alt-2/', 'fa-home']
  My Books : ['My Books', '/books', 'fa-anchor']
  Contact : ['Contact', '/contact', 'fa-plane']
  Author : ['Author', '/author/amuthan', 'fa-user']
single_footer: '<p>A blog about code of conduct for coding. Code Culture &copy; 2016 <a href="/">latest posts</a></p>'
footer_links:
    About: ['About', '/about']
    Writer: ['Code Culture 2016', '/about']
gems:
  - jekyll-gist
# Build settings
markdown: kramdown
